# Numpy

## Installing Numpy

In [21]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [22]:
import numpy as np

## creating 1-D Array

In [32]:
l=[1,2,3,4,5,6]
b=np.array(l)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


## creating 2-D Array

In [37]:
y=[[1,2],[3,4]]
y=np.array(y)
print(type(y))
print(y)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


## creating 3-D Array

In [36]:
z=[[[1,2],[3,4]],[[5,6],[7,8]]]
y=np.array(z)
print(y)
print(type(y))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


# pandas

## pandas installing

In [38]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [39]:
import pandas as  pd

## series in pandas

In [40]:
series=pd.DataFrame([1,2,3,4,5])
print(series)

   0
0  1
1  2
2  3
3  4
4  5


## dataframe in pandas

In [42]:
data={
    'name':['gopal','shubham','ganesh'],
    'age':[10,12,14],
    'city':['gujarat','maharstra','bhanglore'],
    'salary':[10000000,34324342895234,845777828387347]
}
df=pd.DataFrame(data)
print("pandas Dataframe \n")
print(df)

pandas Dataframe 

      name  age       city           salary
0    gopal   10    gujarat         10000000
1  shubham   12  maharstra   34324342895234
2   ganesh   14  bhanglore  845777828387347
